[package]
name = "starry"
version = "1.0.0"
authors = ["dystroy <denys.seguret@gmail.com>"]
edition = "2018"
repository = "https://github.com/Canop/starry"
description = "Current stars history tells only half the story"
keywords = ["github", "star", "story", "history", "graph"]
license = "AGPL-3.0"
readme = "README.md"

[dependencies]
anyhow = "1.0"
argh = "0.1.3"
byo-graphql = "0.1.3"
cli-log = "0.1"
chrono = { version="0.4", features=["serde"] }
csv = "1.1"
directories-next = "2.0"
log = "0.4"
rayon = "1.5"
reqwest = { version = "0.10", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[patch.crates-io]
# byo-graphql = { path = "../byo-graphql" }
